import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GridBackground } from "@/components/GridBackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Samuel Machado | Portfolio",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={cn(
        "bg-background font-sans antialiased dark",
        inter.className
      )}
      >
        <main className="h-screen w-screen overflow-x-hidden">
          <GridBackground>
            {children}
          </GridBackground>
        </main>
      </body>
    </html>
  );
}
